name: meta_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  google_fonts: ^1.1.0
  eva_icons_flutter: ^2.0.0
  email_validator: ^1.0.4
  keyboard_visibility: ^0.5.6
  flutter_statusbarcolor: ^0.2.3
  faker: ^1.2.1
  easy_web_view: ^1.3.0
  video_player: ^0.10.11+1
  shimmer: ^1.1.1
  overlay_support: ^1.0.4
  pull_to_refresh: ^1.5.8
  flutter_spinkit: ^4.1.2+1
  flare_flutter: ^2.0.3
  flutter_tags: ^0.4.8+2
  youtube_player_flutter: ^7.0.0+5
  like_button: ^1.0.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - flares/
